### PR TITLE
Remove TWLBot from apfix and widescreen downloads and add my hosting repo

### PR DESCRIPTION
**Pull request by taserbolt**
The TWLBOT account got privated for some reason, and @RocketRobz has given me express permission to host the files on my own repo to prevent downloads from failing.

image
Proof of permission

### CODE REVIEW

**Comment by NightScript370** [comment]
I think it would be better if you used the `raw.githubusercontent.com` (or does it not actually matter? Dunno, but this is what the old URL used)

**Comment by taserbolt** [comment]
> I think it would be better if you used the `raw.githubusercontent.com` (or does it not actually matter? Dunno, but this is what the old URL used)

@NightScript370 From what I've done, both URLs are the same. I've even tested this on my own console, and it worked.

**Comment by NightScript370** [comment]
I see you made a new commit, but every `https` got changed to `ttps`???

**Comment by taserbolt** [comment]
> I see you made a new commit, but every `https` got changed to `ttps`???

...what?

**Pull request merged**
