### PR TITLE
Update Nazi Zombies: Portable

### PR DESCRIPTION
**Pull request by MotoLegacy**
* Updates Description to be slightly more coherent/relevant
* Updates screenshots to be more representative of the game in its current state, adds screenshots for interface
* Removes installation step for moving the .3DSX binary out of `/3ds/nzportable/` (subsequent updates prevented the new binaries form being used, NZ:P works as expected without this step, Homebrew Launcher identifies the application without issue).

### CODE REVIEW

**Comment by Epicpkmn11** [comment]
The move step is because Universal-Updater allows you to customize your 3DSX install folder, for the vast majority of users it does nothing but if you change that it moves it

Apart from that this looks good to me

**Comment by MotoLegacy** [comment]
Could you clarify on "right spot", should I reintroduce it as `"%3DSX%/nzportable.3dsx"`? I don't fully understand the workflow, so more guidance would be appreciated.

**Comment by MotoLegacy** [comment]
That is what it was before. It wasn't breaking the application, but it was confusing the UU client. The `move` instruction seemed to fail whenever a user had previously installed the application. Meaning the old binary would still be present in `%3DSX%/nzportable.3dsx` whereas the new one was stuck in `/3ds/nzportable/nzportable.3dsx`, confusing users and leaving that old binary lingering, which was problematic for diagnosing issues and general structure.

**Comment by Epicpkmn11** [comment]
Oh, that's really weird... I guess this is fine then but I'll have to take a look into that

**Pull request merged**
