### PR TITLE
Responding to app requests

### LINKED ISSUE #170: RetroArch install fails
See #168

### LINKED ISSUE #175: Citrahold
### Title

Citrahold

### System(s)

3DS

### Categories

Utility, Save Tool

### Unique ID(s)

CTR-HB-CTHD (??)

### Image link

https://raw.githubusercontent.com/regimensocial/Citrahold-3DS/main/assets/banner.png

### Icon link

https://raw.githubusercontent.com/regimensocial/Citrahold-3DS/main/assets/icon.png

### Long description

Citrahold provides you with everything you need to easily move game saves from a physical 3DS to a 3DS emulator on your computer (and vice versa).

It basically allows you to cloud-sync your saves for if you like to play a game across a real 3DS and an emulator.

Please visit [the website](https://www.citrahold.com/) for much more information! It has everything you need in order to set it up.

Checkpoint (or another competent save manager) and an Internet connection are also required.

### Screenshots

https://www.citrahold.com/imagery/screenshots/1.png
https://www.citrahold.com/imagery/screenshots/2.png
https://www.citrahold.com/imagery/screenshots/3.png
https://www.citrahold.com/imagery/screenshots/4.png

### GitHub repository of the app

https://github.com/regimensocial/Citrahold-3DS/

### Author

Jamie Adams, regimensocial

### Short description

Citrahold allows you to sync saves between Citra and your 3DS.

### Source code link

_No response_

### Creation date

_No response_

### Last update date

_No response_

### Website link

https://www.citrahold.com/

### Wiki link

_No response_

### Download page link

_No response_

### Version number

_No response_

### Version title

_No response_

### Download link(s)

Latest: https://github.com/regimensocial/Citrahold-3DS/releases/latest

### Other notes

This requires a little bit of pre-setup to work, please view the guide https://www.citrahold.com/guide and/or the YouTube demonstration https://www.youtube.com/watch?v=MsqyN6I3RAM. 
Checkpoint is also required, or another competent save manager.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #181: Mars3DS
### Title

Mars

### System(s)

3DS

### Categories

Game

### Unique ID(s)

0x2321

### Image link

https://raw.githubusercontent.com/BotRandomness/Mars3DS/master/git-res/logo.png

### Icon link

https://raw.githubusercontent.com/BotRandomness/Mars3DS/master/icon.png

### Long description

# <strong>Mars3DS!</strong>

<em>A lost retro shooter ;) </em>

## <strong>Welcome to Mars!</strong>
Play as Astro, collect the valuable mushrooms, and shoot down the Parasites!

## <strong>Controls</strong>
(+) or CirclePad to move
(A) to shoot
(B) to jump

## Notes
<strong>Check out the github for more technical details</strong>: https://github.com/BotRandomness/Mars3DS

<strong>Enjoy! :)</strong>

### Screenshots

https://raw.githubusercontent.com/BotRandomness/Mars3DS/master/git-res/menu.png
https://raw.githubusercontent.com/BotRandomness/Mars3DS/master/git-res/instru.png
https://raw.githubusercontent.com/BotRandomness/Mars3DS/master/git-res/game.png
https://raw.githubusercontent.com/BotRandomness/Mars3DS/master/git-res/splash.png
https://raw.githubusercontent.com/BotRandomness/Mars3DS/master/git-res/3dsmenu.png

### GitHub repository of the app

https://github.com/BotRandomness/Mars3DS

### Author

Bot Studio

### Short description

Mars3DS, a lost retro shooter. ;)

### Source code link

https://github.com/BotRandomness/Mars3DS

### Creation date

_No response_

### Last update date

_No response_

### Website link

_No response_

### Wiki link

_No response_

### Download page link

https://github.com/BotRandomness/Mars3DS/releases

### Version number

v1.0.0

### Version title

Mars3DS v1.0.0

### Download link(s)

Release page: https://github.com/BotRandomness/Mars3DS/releases

3dsx: https://github.com/BotRandomness/Mars3DS/releases/download/v1.0.0/Mars3D.3dsx
cia: https://github.com/BotRandomness/Mars3DS/releases/download/v1.0.0/Mars3D.cia

### Other notes

_No response_

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #186: Breakup Simulator Portable
### Title

Breakup Simulator Portable

### System(s)

3DS

### Categories

Game

### Unique ID(s)

_No response_

### Image link

https://raw.githubusercontent.com/Dangerbites/BreakupSimulator3DS/main/breakup-banner.png

### Icon link

https://raw.githubusercontent.com/Dangerbites/BreakupSimulator3DS/main/breakup-icon.png

### Long description

In this dating game you need to break up with Cat Grill as soon as possible!! Make decisions to get the emotion meter down before the timer gets to 0!

This port features more endings and a completely portable Breakup Sim experience!!

-- Credits -- ---------------------------

CAT GRILL by DangerBites

Drawing Cat Grill holds up is by Eran

Art and Music by Dangerbites and Haynster

------------------------------------------

### Screenshots

breakup-screenshot

### GitHub repository of the app

https://github.com/Dangerbites/BreakupSimulator3DS

### Author

_No response_

### Short description

_No response_

### Source code link

_No response_

### Creation date

_No response_

### Last update date

_No response_

### Website link

_No response_

### Wiki link

_No response_

### Download page link

_No response_

### Version number

_No response_

### Version title

_No response_

### Download link(s)

_No response_

### Other notes

_No response_

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #187: Spirited DS
### Title

Spirited DS

### System(s)

DS

### Categories

Game

### Unique ID(s)

_No response_

### Image link

_No response_

### Icon link

https://img.itch.zone/aW1nLzE0MDEwNjEyLnBuZw==/315x250%23c/2LmBs3.png

### Long description

Spirited was a series about a rock star ghost who falls in love with an Australian dentist, fresh from the golden age of mad-lib television. Outside of a spartan DVD release, the series produced no merchandise...

Until now.

Today, I introduce you to Spirited DS, a barebones implementation of how I assume Top Trumps works, featuring 64x64 headshots of beloved Spirited characters, on the Nintendo DS. See how I feel these characters rate in 5 absolutely subjective qualities.

Does it fall under fair use? Who knows? But I don't think I'm causing much damage to a thirteen year old series on a sub-240p display, even if there are two of them.

The game is provided as a .nds file, suitable for a flashcart, modded 3DS, or emulator of your choice.

Tragically, there is no sound. Anyone who can help with that probably has better things to do.

Built with NightFoxLib (which feeds off of DevKitPro, LibNDS). Code was written in C++ in Notepad. Python was used to test some logic, and to process pictures from Krita.

Basic rules are: You pick one of five qualities listed on your card. If your value is bigger than your opponent's you win their card, and both cards go to the bottom of your deck. Lose, and it's your opponent's turn. They play by the same rules, and the game ends when one player has no more cards. It was primitive and dated even by late-seventies standards.

### Screenshots

https://img.itch.zone/aW1hZ2UvMjM2NTUyMy8xNDAxMDYxNC5wbmc=/347x500/6j4Uac.png
https://img.itch.zone/aW1hZ2UvMjM2NTUyMy8xNDAxMDYxNS5wbmc=/347x500/hHUlsQ.png
https://img.itch.zone/aW1hZ2UvMjM2NTUyMy8xNDAxMDYxNi5wbmc=/347x500/abe7nq.png

### GitHub repository of the app

https://github.com/KahnerC/SpiritedDS

### Author

KahnerC

### Short description

An uninspired card game for the Nintendo DS.

### Source code link

_No response_

### Creation date

November 2023

### Last update date

November 2023

### Website link

https://kahnerc.itch.io/spirited-ds

### Wiki link

https://kahnerc.itch.io/spirited-ds

### Download page link

https://kahnerc.itch.io/spirited-ds

### Version number

_No response_

### Version title

_No response_

### Download link(s)

https://kahnerc.itch.io/spirited-ds

### Other notes

_No response_

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #202: 3DS vJoy Controller
### Title

3DS vJoy Controller

### System(s)

3DS, DS

### Categories

Utility

### Unique ID(s)

_No response_

### Image link

_No response_

### Icon link

_No response_

### Long description

With this, you can use one or more 3DS consoles as a single, coherent controller on your PC.

Useful if u need a button box or something like that.

Visit the [repo](https://github.com/StringJan/3ds-vJoy-controller) for more info on how to use it.

### Screenshots

_No response_

### GitHub repository of the app

https://github.com/StringJan/3ds-vJoy-controller

### Author

memeToasty, StringJan

### Short description

_No response_

### Source code link

_No response_

### Creation date

_No response_

### Last update date

_No response_

### Website link

_No response_

### Wiki link

_No response_

### Download page link

_No response_

### Version number

_No response_

### Version title

_No response_

### Download link(s)

_No response_

### Other notes

_No response_

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #206: 3DWEB
### Title

3DWEB

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

0x7548

### Image link

https://github.com/WLHQ/3DWEB/blob/main/resources/banner.png

### Icon link

https://github.com/WLHQ/3DWEB/blob/main/resources/icon.png

### Long description

A flexible web server that can handle sd card file reads, crypto operations, system requests and raw memory operations.

### Screenshots

_No response_

### GitHub repository of the app

https://github.com/WLHQ/3DWEB

### Author

WLHQ

### Short description

A web server made in C for the 3DS.

### Source code link

https://github.com/WLHQ/3DWEB

### Creation date

April, 25, 2024

### Last update date

April, 25, 2024

### Website link

_No response_

### Wiki link

_No response_

### Download page link

https://github.com/WLHQ/3DWEB/releases

### Version number

v1.0.0

### Version title

Initial release 

### Download link(s)

_No response_

### Other notes

_No response_

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #208: Pie3DS
### Title

Pie3DS

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

_No response_

### Image link

_No response_

### Icon link

https://raw.githubusercontent.com/amedeo463/pie3ds/main/icon.png

### Long description

Pie3DS - a simple application that calculates Pi.
Written in C with VS code
Compiled with devkitPro
debugged thanks to Docker

### Screenshots

_No response_

### GitHub repository of the app

amedeo463/pie3ds

### Author

amedeo463

### Short description

A simple application that calculates Pi

### Source code link

https://github.com/amedeo463/pie3ds

### Creation date

04 may 2024

### Last update date

04 may 2024

### Website link

https://github.com/amedeo463/pie3ds

### Wiki link

_No response_

### Download page link

https://github.com/amedeo463/pie3ds/releases

### Version number

1.0

### Version title

1.0

### Download link(s)

.3dsx file: https://github.com/amedeo463/pie3ds/releases/download/release/pie3ds.3dsx
.smdh file: https://github.com/amedeo463/pie3ds/releases/download/release/pie3ds.smdh

### Other notes

the .smdh file is needed

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #212: Bullets
### Title

Bullets

### System(s)

3DS

### Categories

Game

### Unique ID(s)

_No response_

### Image link

<a href="https://imgbb.com/">New-Project-1</a><br /><a target='_blank' href='https://imgbb.com/'>host images online free</a><br />

### Icon link

<a href="https://imgbb.com/">New-Project-2</a><br /><a target='_blank' href='https://imgbb.com/'>upload photo to internet free</a><br />

### Long description

Bullets is a very simple and lightweight game for the nintendo 3ds. i made bullets to challenge myself to make a game with no game engine. Dpad to controll player. Start to exit (takes a couple seconds)

### Screenshots

Screenshot 2024-05-10 202803
Screenshot 2024-05-10 202816

### GitHub repository of the app

https://github.com/1Setherson1/Bullets.git

### Author

Sethamphetamine

### Short description

Dodge and weave!

### Source code link

_No response_

### Creation date

_No response_

### Last update date

_No response_

### Website link

_No response_

### Wiki link

_No response_

### Download page link

_No response_

### Version number

_No response_

### Version title

_No response_

### Download link(s)

_No response_

### Other notes

Thanks for your time!

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #216: fMSX3DS
### Title

fMSX3DS

### System(s)

3DS

### Categories

Emulator

### Unique ID(s)

0x736E4

### Image link

_No response_

### Icon link

_No response_

### Long description

fMSX(MSX emulator) port to 3DS. Add new feature such as MSXTurboR emulation and MSX0 emulation.
Also, it add various improvements based on recently analize of MSX hardware
include analize in Japan that is unknown in world wide.

### Screenshots

MSXlogo007big

### GitHub repository of the app

https://github.com/TomiokaH01/fMSX3DS

### Author

h.tomioka

### Short description

fMSX(MSX emulator) port to 3DS. Add many new feature such as MSXTurboR emulation and MSX0 emulation.

### Source code link

https://github.com/TomiokaH01/fMSX3DS

### Creation date

2023/07/26

### Last update date

2024/03/26

### Website link

_No response_

### Wiki link

_No response_

### Download page link

https://github.com/TomiokaH01/fMSX3DS/releases

### Version number

v1.31

### Version title

_No response_

### Download link(s)

_No response_

### Other notes

_No response_

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #218: ScummVM
### Title

ScummVM

### System(s)

3DS, DS

### Categories

Game

### Unique ID(s)

0xFF321

### Image link

https://github.com/scummvm/scummvm/blob/master/backends/platform/3ds/app/banner.png

### Icon link

https://github.com/scummvm/scummvm/blob/master/backends/platform/3ds/app/icon.png

### Long description

ScummVM allows you to play classic graphic point-and-click adventure games, text adventure games, and RPGs, as long as you already have the game data files. ScummVM replaces the executable files shipped with the games, which means you can now play your favorite games on all your favorite devices.

While ScummVM was originally designed to run LucasArts’ SCUMM games, over time support has been added for many other games: see the full list [on our wiki](https://wiki.scummvm.org/index.php?title=Category:Supported_Games). Noteworthy titles include Broken Sword, Myst and Blade Runner, although there are countless other hidden gems to explore.

### Screenshots

_No response_

### GitHub repository of the app

https://github.com/scummvm/scummvm/

### Author

ScummVM Team

### Short description

Point-and-click adventure game engines

### Source code link

_No response_

### Creation date

_No response_

### Last update date

_No response_

### Website link

_No response_

### Wiki link

https://wiki.scummvm.org/index.php?title=Main_Page

### Download page link

https://www.scummvm.org/downloads/

### Version number

_No response_

### Version title

_No response_

### Download link(s)

Release builds: https://www.scummvm.org/downloads/
Daily builds: https://buildbot.scummvm.org/#/dailybuilds

### Other notes

_No response_

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #246: TJAPlayer for 3DS
### Title

TJAPlayer for 3DS

### System(s)

3DS

### Categories

Game

### Unique ID(s)

0xB7655

### Image link

https://raw.githubusercontent.com/LuMariGames/TJAP_3DS/main/resource/icon.png

### Icon link

_No response_

### Long description

TJAPlayer for 3DSを約2年ぶりにTogeToge公認の上、更新しました。

### GitHub repository of the app

https://github.com/LuMariGames/TJAP_3DS

### Author

MarioGames

### Short description

TJAPlayer for 3DS - Music game of the TJA file.

### Source code link

_No response_

### Creation date

2024-07-29

### Last update date

2024-07-29

### Website link

_No response_

### Wiki link

_No response_

### Download page link

_No response_

### Version number

1

### Version title

v1.3.11

### Download link(s)

TJAP_3DS.cia: https://github.com/LuMariGames/TJAP_3DS/releases/download/v1.3.11/TJAP_3DS.cia
TJAP_3DS.3dsx: https://github.com/LuMariGames/TJAP_3DS/releases/download/v1.3.11/TJAP_3DS.3dsx

### Other notes

_No response_

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### LINKED ISSUE #250: NFCheckRem patch
### Title

NFCheckRem

### System(s)

3DS

### Categories

Utility

### Unique ID(s)

_No response_

### Image link

https://raw.githubusercontent.com/Golem642/NFCheckRem/main/NFCheckRem.png

### Icon link

https://raw.githubusercontent.com/Golem642/NFCheckRem/main/NFCheckRem.png

### Long description

Patch for Nintendo consoles to remove the read-only check on amiibos and allow for rewritable Ntag215 NFC tags

# Installation
- Nintendo 3DS : Ensure you have the latest [Luma3DS](https://github.com/LumaTeam/Luma3DS/) version, then go into the folder corresponding to your console and download the .ips file. 
Put this file into your SD card in the following folder : `/luma/sysmodules/` then ensure you have "Enable loading external FIRMs and modules" and "Enable game patching" enabled in the Luma3DS settings (hold SELECT on boot)
- Wii U : (not yet implemented)
- Switch : (not yet implemented)

### Note for 3DS users
The patch will do nothing if wumiibo is enabled, ensure wumiibo is disabled before attempting to scan any Amiibo or NFC tag

# Why ?
When writing an Amiibo to a blank Ntag215 NFC tag with an app such as [TagMo](https://github.com/HiddenRamblings/TagMo), the tag will become read-only on some parts of the data.

This data includes the Amiibo game character id, variant, figure type, model number and series.

This means that if it's read-only, you cannot change the figure stored on the NFC tag, which therefore mean having to buy multiple tags for every Amiibo you want.

# Can't I just use Wumiibo/re_nfpii ?
Well yes but sometimes games won't like when you open their menu and give you intense lag until you restart it, making those amiibo emulation apps unusable on those games.
Moreover, this solution will give you the possibility to have physical tags, so you get the original experience with a few more features + you can easily share it with others as long as they have the patch too

# What does this do ?
This modifies the NFC system module to disable the checks that are made on those areas, yes the console checks if the tag is read-only.

By disabling these checks, this means you can have write-enabled tags and they would still work on consoles with the patch installed

And thus, you can reuse your tag forever without being constrained to have it as one specific Amiibo (you still have to rewrite it every time you want to change it)

# Technical details
See GitHub repository

### Screenshots

_No response_

### GitHub repository of the app

https://github.com/Golem642/NFCheckRem

### Author

Golem64

### Short description

Patch for Nintendo consoles to remove the read-only check on amiibos and allow for rewritable Ntag215 NFC tags

### Source code link

https://github.com/Golem642/NFCheckRem

### Creation date

_No response_

### Last update date

_No response_

### Website link

https://github.com/Golem642/NFCheckRem

### Wiki link

https://github.com/Golem642/NFCheckRem

### Download page link

https://github.com/Golem642/NFCheckRem/tree/main

### Version number

1

### Version title

3DS

### Download link(s)

https://raw.githubusercontent.com/Golem642/NFCheckRem/main/Old%203DS%20and%20Old%202DS/0004013000004002.ips
https://raw.githubusercontent.com/Golem642/NFCheckRem/main/New%203DS%20and%20New%202DS/0004013000004002.ips

### Other notes

Before making an issue saying it's not working, please make sure you :

- Installed the correct patch
- Activated "Enable game patching" And "Allow custom firmware" in Luma3DS settings (hold SELECT on console startup)
- Do not have wumiibo enabled (won't crash, but won't do anything either)
- Used the modified TagMo to flash either : a blank NFC tag, or an already rewritable amiibo nfc Tag. Classic amiibos you flashed with the official TagMo will not be able to be rewritten

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

### PR DESCRIPTION
**Pull request by Golem642**
- Added Citrahold, closes #175 
- Added Mars3DS, closes #181 
- Added Breakup simulator portable, closes #186 
- Added 3DWEB, closes #206 
- Added Pie3DS, closes #208 
- Added Bullets, closes #212 
- Added fMSX3DS, closes #216 
- Added NFCheckRem, closes #250 
- Added Spirited DS, closes #187 
- Added 3DS vJoy Controller, closes #202 
- Replaced TJAP player for 3DS with an updated fork, closes #246 
- Added back retroarch, closes #170 
- Attempting to add scummvm, closes #218 

Waiting for answers for the following apps (might be in a future PR instead) :
- #180
- #185 
- #192 
- #256

### CODE REVIEW

**Comment by Golem642** [comment]
Currently waiting for answers on some app requests, and i don't know what to do for scummvm and retroarch

**Comment by Golem642** [comment]
Just checked the generated retroarch links : they are valid and updated to the latest version, so we should be all good

**Comment by Golem642** [comment]
Note : i didn't include the DS release of scummvm as there is a 3DS standalone release so i felt like the DS one wasn't necessary

**Comment by Epicpkmn11** [comment]
> Note : i didn't include the DS release of scummvm as there is a 3DS standalone release so i felt like the DS one wasn't necessary
> 
> Edit : i also noticed there was a retroarch core for that already, but sometimes it works better as a standalone rather than a retroarch core so i'm letting it in

U-DB is intended to be a resource for both people with 3DS's and DS/DSi’s, so DS versions of apps should be included too

**Comment by Golem642** [comment]
Is there a UU for the DS ?

**Comment by Golem642** [comment]
Marking this as ready for review to atleast commit what i've got rn

**Review by NightScript370 — APPROVED** [review]

**Comment by Golem642** [comment]
Ok so for scummvm i tried to search other examples of cases like this where there are different files in a zip, and i found the "archive" attribute which seems undocumented ?? but i hope it works

**Comment by Golem642** [comment]
Now i'm kinda worried about retroarch and how the files are going to be installed, there might be an empty folder residue.
If there's no objections, can someone merge ? The other 3 issues will be put in a new PR once they answer

**Pull request merged**
